version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_volume:/app-backend/static
    ports:
      - "80:80"
    depends_on:
      - django
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - static_volume:/app-backend/static
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
volumes:
  postgres_data:
  static_volume:
