# Generated by Django 3.1.6 on 2021-02-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
