# Generated by Django 3.1.6 on 2021-02-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_rawairtabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='airtable_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
