# Generated by Django 3.1.6 on 2021-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0005_therapist_airtable_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='airtable_id',
        ),
        migrations.AlterField(
            model_name='therapist',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
